const teams = {
    "atlanta-hawks": {
        name: "Atlanta Hawks",
        abbreviation: "ATL",
        conference: "Eastern Conference",
        division: "Southeast",
        "2526": {
    wins: "46",
    losses: "36",
    winPercent: "56.1%",
    gamesBack: "14.0",
    teamPPG: "118.5",
    teamRPG: "43.5",
    teamAPG: "30.1",
    teamSPG: "9.4",
    teamBPG: "4.7",
    teamFG: "47.4%",
    teamThree: "37.1%"
    },
    "2425": {
    wins: "40",
    losses: "42",
    winPercent: "48.8%",
    gamesBack: "21.0",
    teamPPG: "118.2",
teamRPG: "44.5",
teamAPG: "29.6",
teamSPG: "9.7",
teamBPG: "5.1",
teamFG: "47.2%",
teamThree: "35.8%"
},
        roster: [

    { name: "Nickeil Alexander-Walker", position: "G" },
    { name: "Dyson Daniels", position: "G" },
    { name: "RayJ Dennis", position: "G" },
    { name: "Luguentz Dort", position: "G" },
    { name: "Zuby Ejiofor", position: "F" },
    { name: "Dorian Finney-Smith", position: "F" },
    { name: "Kingston Flemings", position: "G" },
    { name: "Keshon Gilbert", position: "G" },
    { name: "Mouhamed Gueye", position: "F" },
    { name: "Jalen Johnson", position: "F" },
    { name: "Keon Johnson", position: "G" },
    { name: "Corey Kispert", position: "F" },
    { name: "Jock Landale", position: "C" },
    { name: "CJ McCollum", position: "G" },
    { name: "Asa Newell", position: "F" },
    { name: "Onyeka Okongwu", position: "F" },
    { name: "Henri Veesaar", position: "C" },
    { name: "Aaron Wiggins", position: "G" },
    { name: "Jalen Wilson", position: "F" }
]
    },
    "boston-celtics": {
    name: "Boston Celtics",
    abbreviation: "BOS",
    conference: "Eastern Conference",
    division: "Atlantic",
    "2526": {
        wins: "56",
        losses: "26",
        winPercent: "68.3%",
        gamesBack: "4.0",
        teamPPG: "114.9",
        teamRPG: "46.4",
        teamAPG: "24.6",
        teamSPG: "7.1",
        teamBPG: "5.0",
        teamFG: "46.7%",
        teamThree: "36.7%"
    },
    "2425": {
    wins: "61",
    losses: "21",
    winPercent: "74.4%",
    gamesBack: "3.0",
    teamPPG: "116.3",
teamRPG: "45.3",
teamAPG: "26.1",
teamSPG: "7.18",
teamBPG: "5.51",
teamFG: "46.2%",
teamThree: "36.8%"

},

    roster: [
        { name: "Chris Cenac Jr.", position: "F-C"},
        { name: "Mike Conley", position: "G" },
        { name: "Tucker DeVries", position: "G-F" },
        { name: "Luka Garza", position: "F-C" },
        { name: "Paul George", position: "G-F" },
        { name: "Hugo Gonzalez", position: "G-F" },
        { name: "Ron Harper Jr.", position: "G-F" },
        { name: "Sam Hauser", position: "F" },
        { name: "Dillon Mitchell", position: "F" },
        { name: "Payton Pritchard", position: "G" },
        { name: "Neemias Queta", position: "C" },
        { name: "Mitchell Robinson", position: "C" },
        { name: "Baylor Scheierman", position: "G-F" },
        { name: "Max Shulga", position: "G" },
        { name: "Jayson Tatum", position: "F" },
        { name: "Milos Uzan", position: "G" },
        { name: "Jordan Walsh", position: "G-F" },
        { name: "Derrick White", position: "G" },
        { name: "Amari Williams", position: "F-C" }
    ]
},
    "brooklyn-nets": {
        name: "Brooklyn Nets",
        abbreviation: "BKN",
        conference: "Eastern Conference",
        division: "Atlantic",
        "2526": {
        wins: "20",
        losses: "62",
        winPercent: "24.4%",
        gamesBack: "40.0",
        teamPPG: "105.9",
        teamRPG: "39.3",
        teamAPG: "25.0",
        teamSPG: "8.0",
        teamBPG: "4.3",
        teamFG: "44.3%",
        teamThree: "34.0%"
    },
    "2425": {
    wins: "26",
    losses: "56",
    winPercent: "31.7%",
    gamesBack: "35.0",
    teamPPG: "105.1",
teamRPG: "41.3",
teamAPG: "25.2",
teamSPG: "7.8",
teamBPG: "4.3",
teamFG: "43.7%",
teamThree: "34.4%"
},
    roster: [
    { name: "Tyler Bilodeau", position: "F" },
    { name: "Mikel Brown Jr.", position: "G" },
    { name: "Noah Clowney", position: "F" },
    { name: "Egor Demin", position: "G" },
    { name: "Keon Ellis", position: "G" },
    { name: "Tyson Etienne", position: "G" },
    { name: "Joshua Jefferson", position: "F" },
    { name: "Chaney Johnson", position: "F" },
    { name: "E.J. Liddell", position: "F" },
    { name: "Terance Mann", position: "G" },
    { name: "Josh Minott", position: "F" },
    { name: "Michael Porter Jr.", position: "F" },
    { name: "Drake Powell", position: "G" },
    { name: "Julius Randle", position: "F" },
    { name: "Ben Saraf", position: "G" },
    { name: "Day'Ron Sharpe", position: "C" },
    { name: "Nolan Traore", position: "G" },
    { name: "Moritz Wagner", position: "F" },
    { name: "Danny Wolf", position: "F" }
]
    },
    "charlotte-hornets": {
        name: "Charlotte Hornets",
        abbreviation: "CHA",
        conference: "Eastern Conference",
        division: "Southeast",
        "2526": {
        wins: "44",
        losses: "38",
        winPercent: "53.7%",
        gamesBack: "16.0",
        teamPPG: "116.0",
        teamRPG: "46.1",
        teamAPG: "26.3",
        teamSPG: "7.0",
        teamBPG: "4.5",
        teamFG: "46.0%",
        teamThree: "37.8%"
    },
    "2425": {
    wins: "19",
    losses: "63",
    winPercent: "23.2%",
    gamesBack: "42.0",
    teamPPG: "105.1",
teamRPG: "45.2",
teamAPG: "24.3",
teamSPG: "7.4",
teamBPG: "4.5",
teamFG: "43.0%",
teamThree: "33.9%"
},
    roster: [
    { name: "Grayson Allen", position: "G" },
    { name: "Christian Anderson", position: "G" },
    { name: "Pat Connaughton", position: "G" },
    { name: "Moussa Diabate", position: "F" },
    { name: "PJ Hall", position: "C" },
    { name: "Sion James", position: "G" },
    { name: "Ryan Kalkbrenner", position: "C" },
    { name: "Kon Knueppel", position: "G" },
    { name: "Liam McNeeley", position: "G" },
    { name: "Brandon Miller", position: "F" },
    { name: "Ryan Nembhard", position: "G" },
    { name: "Royce O'Neale", position: "F" },
    { name: "Naz Reid", position: "C" },
    { name: "Tidjane Salaun", position: "F" },
    { name: "Dennis Schroder", position: "G" },
    { name: "Hannes Steinbach", position: "F" },
    { name: "Coby White", position: "G" },
    { name: "Grant Williams", position: "F" }
]
    },
    "chicago-bulls": {
        name: "Chicago Bulls",
        abbreviation: "CHI",
        conference: "Eastern Conference",
        division: "Central",
        "2526": {
            wins: "31",
            losses: "51",
            winPercent: "37.8%",
            gamesBack: "29.0",
            teamPPG: "116.3",
teamRPG: "45.0",
teamAPG: "28.5",
teamSPG: "7.6",
teamBPG: "5.0",
teamFG: "46.9%",
teamThree: "35.6%"
        },
        "2425": {
    wins: "39",
    losses: "43",
    winPercent: "47.6%",
    gamesBack: "22.0",
    teamPPG: "117.8",
teamRPG: "45.9",
teamAPG: "29.1",
teamSPG: "7.6",
teamBPG: "4.7",
teamFG: "47.0%",
teamThree: "36.7%"
},
        roster: [
    { name: "Tobe Awaka", position: "F" },
    { name: "Matas Buzelis", position: "F" },
    { name: "Nic Claxton", position: "C" },
    { name: "Zach Collins", position: "F" },
    { name: "Buddy Hield", position: "G" },
    { name: "Noa Essengue", position: "F" },
    { name: "Josh Giddey", position: "G" },
    { name: "Buddy Hield", position: "G" },
    { name: "Tre Jones", position: "G" },
    { name: "Leonard Miller", position: "F" },
    { name: "Isaac Okoro", position: "F" },
    { name: "Norman Powell", position: "G" },
    { name: "Jalen Smith", position: "F" },
    { name: "Dailyn Swain", position: "G" },
    { name: "Patrick Williams", position: "F" },
    { name: "Caleb Wilson", position: "F" },
]
    },
    "cleveland-cavaliers": {
        name: "Cleveland Cavaliers",
        abbreviation: "CLE",
        conference: "Eastern Conference",
        division: "Central",
        "2526": {
            wins: "52",
            losses: "30",
            winPercent: "63.4%",
            gamesBack: "8.0",
            teamPPG: "119.5",
teamRPG: "44.4",
teamAPG: "28.3",
teamSPG: "8.5",
teamBPG: "5.0",
teamFG: "48.2%",
teamThree: "36.0%"
        },
        "2425": {
    wins: "64",
    losses: "18",
    winPercent: "78.0%",
    gamesBack: "-",
    teamPPG: "121.9",
teamRPG: "45.4",
teamAPG: "28.1",
teamSPG: "8.2",
teamBPG: "4.3",
teamFG: "49.1%",
teamThree: "38.3%"
},
        roster: [
    { name: "Jarrett Allen", position: "C" },
    { name: "Thomas Bryant", position: "C" },
    { name: "Khalifa Diop", position: "C" },
    { name: "Tristan Enaruna", position: "F" },
    { name: "James Harden", position: "G" },
    { name: "Mario Hezonja", position: "F" },
    { name: "Sam Merrill", position: "G" },
    { name: "Riley Minix", position: "F" },
    { name: "Donovan Mitchell", position: "G" },
    { name: "Evan Mobley", position: "C" },
    { name: "Craig Porter Jr.", position: "G" },
    { name: "Tyrese Proctor", position: "G" },
    { name: "Olivier Sarr", position: "F" },
    { name: "Meleek Thomas", position: "G" },
    { name: "Nae'Qwan Tomlin", position: "F" },
    { name: "Jaylon Tyson", position: "G" },
    { name: "Ernest Udeh Jr.", position: "C" },
    { name: "Peyton Watson", position: "G" }
]
    },
    "dallas-mavericks": {
        name: "Dallas Mavericks",
        abbreviation: "DAL",
        conference: "Western Conference",
        division: "Southwest",
        "2526": {
            wins: "26",
            losses: "56",
            winPercent: "31.7%",
            gamesBack: "38.0",
             teamPPG: "114.1",
    teamRPG: "44.7",
    teamAPG: "25.3",
    teamSPG: "7.5",
    teamBPG: "5.2",
    teamFG: "46.6%",
    teamThree: "34.4%"
        },
        "2425": {
    wins: "39",
    losses: "43",
    winPercent: "47.6%",
    gamesBack: "29.0",
    teamPPG: "114.2",
teamRPG: "43.0",
teamAPG: "25.2",
teamSPG: "7.8",
teamBPG: "5.4",
teamFG: "47.9%",
teamThree: "36.4%"
},
        roster: [
    { name: "Santi Aldama", position: "F" },
    { name: "Tarik Biberovic", position: "F" },
    { name: "Max Christie", position: "G" },
    { name: "Moussa Cisse", position: "C" },
    { name: "Sergio de Larrea", position: "F" },
    { name: "Cooper Flagg", position: "F" },
    { name: "Daniel Gafford", position: "F" },
    { name: "Jett Howard", position: "G" },
    { name: "Kyrie Irving", position: "G" },
    { name: "Vsevolod Ishchenko", position: "G" },
    { name: "Morez Johnson Jr.", position: "F" },
    { name: "Tobi Lawal", position: "F" },
    { name: "Dereck Lively II", position: "C" },
    { name: "Seth Lundy", position: "G" },
    { name: "Naji Marshall", position: "F" },
    { name: "Caleb Martin", position: "F" },
    { name: "John Poulakidas", position: "G" },
    { name: "Dwight Powell", position: "F" },
    { name: "Zaccharie Risacher", position: "F" },
    { name: "Marcus Sasser", position: "G" },
    { name: "P.J. Washington", position: "F" }
]
    },
    "denver-nuggets": {
        name: "Denver Nuggets",
        abbreviation: "DEN",
        conference: "Western Conference",
        division: "Northwest",
        "2526": {
            wins: "54",
            losses: "28",
            winPercent: "65.9%",
            gamesBack: "10.0",
            teamPPG: "122.1",
teamRPG: "44.0",
teamAPG: "29.0",
teamSPG: "6.8",
teamBPG: "4.0",
teamFG: "49.6%",
teamThree: "39.6%"
        },
        "2425": {
    wins: "50",
    losses: "32",
    winPercent: "61.0%",
    gamesBack: "18.0",
    teamPPG: "120.8",
teamRPG: "45.7",
teamAPG: "31.0",
teamSPG: "8.0",
teamBPG: "4.9",
teamFG: "50.6%",
teamThree: "37.6%"
},
        roster: [
    { name: "Marvin Bagley III", position: "F" },
    { name: "Christian Braun", position: "G" },
    { name: "Trevon Brazile", position: "F" },
    { name: "DeMar DeRozan", position: "G" },
    { name: "Alpha Diallo", position: "F" },
    { name: "Aaron Gordon", position: "F" },
    { name: "DaRon Holmes II", position: "F" },
    { name: "Bryce Hopkins", position: "F" },
    { name: "Cameron Johnson", position: "F" },
    { name: "Nikola Jokic", position: "C" },
    { name: "Spencer Jones", position: "F" },
    { name: "Tyus Jones", position: "G" },
    { name: "Jamal Murray", position: "G" },
    { name: "Zeke Nnaji", position: "F" },
    { name: "David Roddy", position: "F" },
    { name: "KJ Simpson", position: "G" },
    { name: "Julian Strawther", position: "G" },
    { name: "Lonnie Walker IV", position: "G" },
    { name: "Cam Whitmore", position: "F" }
]
    },
    "detroit-pistons": {
        name: "Detroit Pistons",
        abbreviation: "DET",
        conference: "Eastern Conference",
        division: "Central",
        "2526": {
            wins: "60",
            losses: "22",
            winPercent: "73.2%",
            gamesBack: "-",
            teamPPG: "117.8",
teamRPG: "45.6",
teamAPG: "27.8",
teamSPG: "10.4",
teamBPG: "6.4",
teamFG: "48.5%",
teamThree: "35.6%"
        },
        "2425": {
    wins: "44",
    losses: "38",
    winPercent: "53.7%",
    gamesBack: "20.0",
    teamPPG: "115.5",
teamRPG: "44.8",
teamAPG: "26.4",
teamSPG: "8.0",
teamBPG: "5.3",
teamFG: "47.6%",
teamThree: "36.2%"
},
        roster: [
    { name: "John Collins", position: "F" },
    { name: "Cade Cunningham", position: "G" },
    { name: "Jalen Duren", position: "C" },
    { name: "Javonte Green", position: "G" },
    { name: "Elijah Harkless", position: "G" },
    { name: "Gary Harris", position: "G" },
    { name: "Ronald Holland II", position: "F" },
    { name: "Kevin Huerter", position: "G" },
    { name: "Daniss Jenkins", position: "G" },
    { name: "Isaiah Joe", position: "G" },
    { name: "Isaac Jones", position: "C" },
    { name: "Chaz Lanier", position: "G" },
    { name: "Wendell Moore Jr.", position: "F" },
    { name: "Ebuka Okorie", position: "G" },
    { name: "Ugonna Onyenso", position: "C" },
    { name: "Taurean Prince", position: "F" },
    { name: "Paul Reed", position: "F" },
    { name: "Duncan Robinson", position: "F" },
    { name: "Tolu Smith", position: "F" },
    { name: "Ausar Thompson", position: "G" }
]
    },
    "golden-state-warriors": {
        name: "Golden State Warriors",
        abbreviation: "GSW",
        conference: "Western Conference",
        division: "Pacific",
        "2526": {
        wins: "37",
        losses: "45",
        winPercent: "45.1%",
        gamesBack: "27.0",
        teamPPG: "114.6",
        teamRPG: "42.3",
        teamAPG: "28.9",
        teamSPG: "9.7",
        teamBPG: "4.2",
        teamFG: "46.1%",
        teamThree: "35.6%",
        },
        "2425": {
    wins: "48",
    losses: "34",
    winPercent: "58.5%",
    gamesBack: "20.0",
    teamPPG: "113.8",
teamRPG: "45.4",
teamAPG: "29.1",
teamSPG: "9.4",
teamBPG: "4.8",
teamFG: "45.1%",
teamThree: "36.4%"
},

        roster: [
        { name: "Charles Bassey", position: "C" },
        { name: "Jimmy Butler III", position: "F" },
        { name: "LJ Cryer", position: "G" },
        { name: "Stephen Curry", position: "G" },
        { name: "Draymond Green", position: "F" },
        { name: "Al Horford", position: "C" },
        { name: "Lajae Jones", position: "G" },
        { name: "Yaxel Lendeborg", position: "F" },
        { name: "Malevy Leons", position: "F" },
        { name: "De'Anthony Melton", position: "G" },
        { name: "Moses Moody", position: "G" },
        { name: "Georges Niang", position: "F" },
        { name: "Gary Payton II", position: "G" },
        { name: "Brandin Podziemski", position: "G" },
        { name: "Kristaps Porzingis", position: "C" },
        { name: "Will Richard", position: "G" },
        { name: "Gui Santos", position: "F" },
        { name: "Brandon Williams", position: "G" },
        { name: "Nate Williams", position: "G" }
    ]
    },
    "houston-rockets": {
        name: "Houston Rockets",
        abbreviation: "HOU",
        conference: "Western Conference",
        division: "Southwest",
        "2526": {
            wins: "52",
            losses: "30",
            winPercent: "63.4%",
            gamesBack: "12.0",
            teamPPG: "115.2",
teamRPG: "48.1",
teamAPG: "25.4",
teamSPG: "8.5",
teamBPG: "5.8",
teamFG: "47.9%",
teamThree: "36.4%"
        },
        "2425": {
    wins: "52",
    losses: "30",
    winPercent: "63.4%",
    gamesBack: "16.0",
    teamPPG: "114.3",
teamRPG: "48.5",
teamAPG: "23.3",
teamSPG: "8.4",
teamBPG: "5.0",
teamFG: "45.5%",
teamThree: "35.3%"
},
        roster: [
    { name: "Steven Adams", position: "C" },
    { name: "Bogdan Bogdanovic", position: "G" },
    { name: "Clint Capela", position: "C" },
    { name: "Rafael Castro", position: "C" },
    { name: "Quadir Copeland", position: "G" },
    { name: "Isaiah Crawford", position: "F" },
    { name: "Kevin Durant", position: "F" },
    { name: "Tari Eason", position: "F" },
    { name: "Sean Pedulla", position: "G" },
    { name: "Alperen Sengun", position: "C" },
    { name: "Reed Sheppard", position: "G" },
    { name: "Marcus Smart", position: "G" },
    { name: "Jabari Smith Jr.", position: "F" },
    { name: "Jae'Sean Tate", position: "F" },
    { name: "Amen Thompson", position: "G" },
    { name: "Bruce Thornton", position: "G" },
    { name: "Fred VanVleet", position: "G" }
]
    },
    "indiana-pacers": {
        name: "Indiana Pacers",
        abbreviation: "IND",
        conference: "Eastern Conference",
        division: "Central",
        "2526": {
            wins: "19",
            losses: "63",
            winPercent: "23.2%",
            gamesBack: "41.0",
            teamPPG: "112.4",
teamRPG: "41.9",
teamAPG: "27.7",
teamSPG: "7.4",
teamBPG: "4.6",
teamFG: "45.8%",
teamThree: "35.6%"
        },
        "2425": {
    wins: "50",
    losses: "32",
    winPercent: "61.0%",
    gamesBack: "14.0",
    teamPPG: "117.4",
teamRPG: "41.8",
teamAPG: "29.2",
teamSPG: "8.5",
teamBPG: "5.5",
teamFG: "48.8%",
teamThree: "36.8%"
},
        roster: [
    { name: "Kobe Brown", position: "G" },
    { name: "Johnny Furphy", position: "G" },
    { name: "Tyrese Haliburton", position: "G" },
    { name: "Jay Huff", position: "C" },
    { name: "Quenton Jackson", position: "G" },
    { name: "T.J. McConnell", position: "G" },
    { name: "Larry Nance Jr.", position: "F" },
    { name: "Andrew Nembhard", position: "G" },
    { name: "Aaron Nesmith", position: "G" },
    { name: "Kelly Oubre Jr.", position: "G" },
    { name: "Ben Sheppard", position: "G" },
    { name: "Pascal Siakam", position: "F" },
    { name: "Jalen Slawson", position: "F" },
    { name: "Braden Smith", position: "G" },
    { name: "Obi Toppin", position: "F" },
    { name: "Jarace Walker", position: "F" },
    { name: "Ivica Zubac", position: "C" }
]
    },
    "los-angeles-clippers": {
        name: "LA Clippers",
        abbreviation: "LAC",
        conference: "Western Conference",
        division: "Pacific",
        "2526": {
        wins: "42",
        losses: "40",
        winPercent: "51.2%",
            gamesBack: "22.0",
        teamPPG: "113.8",
teamRPG: "40.6",
teamAPG: "23.7",
teamSPG: "9.0",
teamBPG: "4.9",
teamFG: "48.4%",
teamThree: "36.8%"
        },
        "2425": {
    wins: "50",
    losses: "32",
    winPercent: "61.0%",
    gamesBack: "18.0",
    teamPPG: "112.9",
teamRPG: "43.8",
teamAPG: "25.2",
teamSPG: "9.4",
teamBPG: "4.5",
teamFG: "48.2%",
teamThree: "37.3%"

},
        roster: [
    { name: "Bradley Beal", position: "G" },
    { name: "Cam Christie", position: "G" },
    { name: "Gradey Dick", position: "G" },
    { name: "Kris Dunn", position: "G" },
    { name: "Darius Garland", position: "G" },
    { name: "Rui Hachimura", position: "F" },
    { name: "Brandon Ingram", position: "F" },
    { name: "Isaiah Jackson", position: "F" },
    { name: "Derrick Jones Jr.", position: "F" },
    { name: "Brook Lopez", position: "C" },
    { name: "Nick Martinelli", position: "F" },
    { name: "Baba Miller", position: "F" },
    { name: "Jordan Miller", position: "G" },
    { name: "Narcisse Ngoy", position: "F" },
    { name: "Yanic Konan Niederhauser", position: "C" },
    { name: "Jalen Pickett", position: "G" },
    { name: "Kobe Sanders", position: "G" },
    { name: "Max Strus", position: "G" },
    { name: "Keaton Wagler", position: "G" },
    { name: "TyTy Washington Jr.", position: "G" }
]
    },
    "los-angeles-lakers": {
        name: "Los Angeles Lakers",
        abbreviation: "LAL",
        conference: "Western Conference",
        division: "Pacific",
        "2526": {
        wins: "53",
        losses: "29",
        winPercent: "64.6%",
            gamesBack: "11.0",
            teamPPG: "116.3",
teamRPG: "41.0",
teamAPG: "25.9",
teamSPG: "8.5",
teamBPG: "4.3",
teamFG: "50.2%",
teamThree: "35.9%"
    
        },
        "2425": {
    wins: "50",
    losses: "32",
    winPercent: "61.0%",
    gamesBack: "18.0",
    teamPPG: "113.4",
teamRPG: "42.4",
teamAPG: "26.0",
teamSPG: "7.7",
teamBPG: "4.5",
teamFG: "47.9%",
teamThree: "36.6%"
},
        roster: [
    { name: "Cameron Carr", position: "G" },
    { name: "Luka Doncic", position: "G" },
    { name: "Quentin Grimes", position: "G" },
    { name: "Jaden Hardy", position: "G" },
    { name: "Bronny James", position: "G" },
    { name: "Meechie Johnson", position: "G" },
    { name: "Walker Kessler", position: "C" },
    { name: "Dalton Knecht", position: "F" },
    { name: "Jake LaRavia", position: "F" },
    { name: "Kevon Looney", position: "F" },
    { name: "Sandro Mamukelashvili", position: "F" },
    { name: "Chris Manon", position: "G" },
    { name: "AK Okereke", position: "F" },
    { name: "Austin Reaves", position: "G" },
    { name: "Chase Ross", position: "G" },
    { name: "Collin Sexton", position: "G" },
    { name: "Adou Thiero", position: "F" },
    { name: "Matisse Thybulle", position: "G" },
    { name: "Jarred Vanderbilt", position: "F" },
    { name: "Ziaire Williams", position: "F" }
]
    },
    "memphis-grizzlies": {
        name: "Memphis Grizzlies",
        abbreviation: "MEM",
        conference: "Western Conference",
        division: "Southwest",
        "2526": {
            wins: "25",
            losses: "57",
            winPercent: "30.5%",
            gamesBack: "39.0",
            teamPPG: "114.7",
teamRPG: "42.1",
teamAPG: "27.8",
teamSPG: "8.8",
teamBPG: "4.8",
teamFG: "45.6%",
teamThree: "35.3%"
        },
        "2425": {
    wins: "48",
    losses: "34",
    winPercent: "58.5%",
    gamesBack: "20.0",
    teamPPG: "121.7",
teamRPG: "47.3",
teamAPG: "28.4",
teamSPG: "8.9",
teamBPG: "5.6",
teamFG: "47.9%",
teamThree: "36.7%"
},
        roster: [
    { name: "Cameron Boozer", position: "F" },
    { name: "Walter Clayton Jr.", position: "G" },
    { name: "Cedric Coward", position: "F" },
    { name: "Zach Edey", position: "C" },
    { name: "Jerami Grant", position: "F" },
    { name: "Brendan Hausen", position: "F" },
    { name: "Jordan Hawkins", position: "G" },
    { name: "Taylor Hendricks", position: "F" },
    { name: "GG Jackson", position: "F" },
    { name: "Ty Jerome", position: "G" },
    { name: "Karim Lopez", position: "F" },
    { name: "Jahmai Mashack", position: "G" },
    { name: "Kris Murray", position: "F" },
    { name: "Micah Peavy", position: "G" },
    { name: "Scotty Pippen Jr.", position: "G" },
    { name: "Quinten Post", position: "C" },
    { name: "Olivier-Maxence Prosper", position: "F" },
    { name: "Richie Saunders", position: "G" },
    { name: "Javon Small", position: "G" },
    { name: "Cam Spencer", position: "G" },
    { name: "Isaiah Stewart", position: "F" },
    { name: "Jaylen Wells", position: "F" }
]
    },
    "miami-heat": {
        name: "Miami Heat",
        abbreviation: "MIA",
        conference: "Eastern Conference",
        division: "Southeast",
        "2526": {
            wins: "43",
            losses: "39",
            winPercent: "52.4%",
            gamesBack: "17.0",
            teamPPG: "120.9",
teamRPG: "46.3",
teamAPG: "29.0",
teamSPG: "8.6",
teamBPG: "4.3",
teamFG: "46.8%",
teamThree: "36.1%"
        },
        "2425": {
    wins: "37",
    losses: "45",
    winPercent: "45.1%",
    gamesBack: "27.0",
    teamPPG: "110.6",
teamRPG: "43.4",
teamAPG: "26.4",
teamSPG: "8.1",
teamBPG: "3.8",
teamFG: "46.5%",
teamThree: "36.7%"
},
        roster: [
    { name: "Bam Adebayo", position: "C" },
    { name: "Giannis Antetokounmpo", position: "F" },
    { name: "Ryan Conwell", position: "G" },
    { name: "Tre Donaldson", position: "G" },
    { name: "Simone Fontecchio", position: "F" },
    { name: "Myron Gardner", position: "F" },
    { name: "Vladislav Goldin", position: "C" },
    { name: "J'Vonne Hadley", position: "F" },
    { name: "Tim Hardaway Jr.", position: "G" },
    { name: "Keshad Johnson", position: "F" },
    { name: "Nikola Jovic", position: "F" },
    { name: "Trevor Keels", position: "G" },
    { name: "Pelle Larsson", position: "G" },
    { name: "Bez Mbeng", position: "G" },
    { name: "Davion Mitchell", position: "G" },
    { name: "Bobby Portis", position: "F" },
    { name: "Nick Richards", position: "C" },
    { name: "Dru Smith", position: "G" },
    { name: "Klay Thompson", position: "G" },
    { name: "Andrew Wiggins", position: "F" }
]
    },
    "milwaukee-bucks": {
        name: "Milwaukee Bucks",
        abbreviation: "MIL",
        conference: "Eastern Conference",
        division: "Central",
        "2526": {
        wins: "32",
        losses: "50",
        winPercent: "39.0%",
            gamesBack: "28.0",
            teamPPG: "110.6",
teamRPG: "40.7",
teamAPG: "25.8",
teamSPG: "7.4",
teamBPG: "4.0",
teamFG: "47.7%",
teamThree: "38.7%"
        },
        "2425": {
    wins: "48",
    losses: "34",
    winPercent: "58.5%",
    gamesBack: "16.0",
    teamPPG: "115.5",
teamRPG: "43.4",
teamAPG: "25.5",
teamSPG: "7.3",
teamBPG: "4.7",
teamFG: "48.6%",
teamThree: "38.7%"
},
        roster: [
    { name: "Nate Ament", position: "F" },
    { name: "Brayden Burries", position: "G" },
    { name: "Ousmane Dieng", position: "F" },
    { name: "AJ Green", position: "G" },
    { name: "Tyler Herro", position: "G" },
    { name: "Kasparas Jakucionis", position: "G" },
    { name: "Jaime Jaquez Jr.", position: "F" },
    { name: "Kam Jones", position: "G" },
    { name: "Kyle Kuzma", position: "F" },
    { name: "Caris LeVert", position: "G" },
    { name: "Malique Lewis", position: "F" },
    { name: "Bogoljub Markovic", position: "F" },
    { name: "Pete Nance", position: "F" },
    { name: "Kevin Porter Jr.", position: "G" },
    { name: "Ryan Rollins", position: "G" },
    { name: "Cormac Ryan", position: "G" },
    { name: "Jericho Sims", position: "C" },
    { name: "Gary Trent Jr.", position: "G" },
    { name: "Myles Turner", position: "C" },
    { name: "Kel'el Ware", position: "C" }
]
    },
    "minnesota-timberwolves": {
        name: "Minnesota Timberwolves",
        abbreviation: "MIN",
        conference: "Western Conference",
        division: "Northwest",
        "2526": {
        wins: "49",
        losses: "33",
        winPercent: "59.8%",
            gamesBack: "15.0",
            teamPPG: "118.0",
teamRPG: "44.1",
teamAPG: "26.1",
teamSPG: "8.7",
teamBPG: "5.8",
teamFG: "48.1%",
teamThree: "37.0%"
        },
        "2425": {
    wins: "49",
    losses: "33",
    winPercent: "59.8%",
    gamesBack: "19.0",
    teamPPG: "114.3",
teamRPG: "44.2",
teamAPG: "26.0",
teamSPG: "8.0",
teamBPG: "5.0",
teamFG: "46.7%",
teamThree: "37.8%"
},
        roster: [
    { name: "LaMelo Ball", position: "G" },
    { name: "Joan Beringer", position: "F" },
    { name: "Jaylen Clark", position: "G" },
    { name: "Donte DiVincenzo", position: "G" },
    { name: "Ayo Dosunmu", position: "G" },
    { name: "Anthony Edwards", position: "G" },
    { name: "Isaiah Evans", position: "G" },
    { name: "Enrique Freeman", position: "F" },
    { name: "Rudy Gobert", position: "C" },
    { name: "Bones Hyland", position: "G" },
    { name: "Trey Kaufman-Renn", position: "F" },
    { name: "John Konchar", position: "G" },
    { name: "Jonathan Kuminga", position: "F" },
    { name: "Trey Lyles", position: "F" },
    { name: "Jaden McDaniels", position: "F" },
    { name: "Julian Phillips", position: "F" },
    { name: "Zyon Pullin", position: "G" },
    { name: "Terrence Shannon Jr.", position: "G" },
    { name: "Cody Williams", position: "F" },
    { name: "Rocco Zikarsky", position: "C" }
]
    },
    "new-orleans-pelicans": {
        name: "New Orleans Pelicans",
        abbreviation: "NOP",
        conference: "Western Conference",
        division: "Southwest",
        "2526": {
            wins: "26",
            losses: "56",
            winPercent: "31.7%",
            gamesBack: "38.0",
            teamPPG: "115.5",
teamRPG: "43.9",
teamAPG: "25.1",
teamSPG: "8.9",
teamBPG: "5.2",
teamFG: "46.6%",
teamThree: "34.7%"
        },
        "2425": {
    wins: "21",
    losses: "61",
    winPercent: "25.6%",
    gamesBack: "47.0",
    teamPPG: "109.8",
teamRPG: "43.6",
teamAPG: "25.8",
teamSPG: "8.5",
teamBPG: "5.2",
teamFG: "45.2%",
teamThree: "34.7%"
},
        roster: [
    { name: "Saddiq Bey", position: "G" },
    { name: "Malik Dia", position: "F" },
    { name: "Jeremiah Fears", position: "G" },
    { name: "AJ Johnson", position: "G" },
    { name: "Herbert Jones", position: "F" },
    { name: "DeAndre Jordan", position: "C" },
    { name: "Bennedict Mathurin", position: "G" },
    { name: "Karlo Matkovic", position: "F" },
    { name: "Bryce McGowens", position: "G" },
    { name: "Yves Missi", position: "C" },
    { name: "Trey Murphy III", position: "F" },
    { name: "Dejounte Murray", position: "G" },
    { name: "Josh Oduro", position: "C" },
    { name: "Jaron Pierre Jr.", position: "G" },
    { name: "Jordan Poole", position: "G" },
    { name: "Derik Queen", position: "C" },
    { name: "Julian Reese", position: "F" },
    { name: "Trendon Watford", position: "F" },
    { name: "Zion Williamson", position: "F" }
]
    },
    "new-york-knicks": {
        name: "New York Knicks",
        abbreviation: "NYK",
        conference: "Eastern Conference",
        division: "Atlantic",
        "2526": {
        wins: "53",
        losses: "29",
        winPercent: "64.6%",
        gamesBack: "7.0",
        teamPPG: "116.5",
teamRPG: "45.6",
teamAPG: "27.4",
teamSPG: "8.1",
teamBPG: "3.9",
teamFG: "47.8%",
teamThree: "37.3%"
        },
        "2425": {
    wins: "51",
    losses: "31",
    winPercent: "62.2%",
    gamesBack: "13.0",
    teamPPG: "115.8",
teamRPG: "42.6",
teamAPG: "27.5",
teamSPG: "8.2",
teamBPG: "4.0",
teamFG: "48.6%",
teamThree: "36.9%"
},
        roster: [
    { name: "Jose Alvarado", position: "G" },
    { name: "OG Anunoby", position: "F" },
    { name: "Mikal Bridges", position: "G" },
    { name: "Jalen Brunson", position: "G" },
    { name: "Jordan Clarkson", position: "G" },
    { name: "Pacome Dadiet", position: "F" },
    { name: "Mohamed Diawara", position: "F" },
    { name: "Andre Drummond", position: "C" },
    { name: "Josh Hart", position: "G" },
    { name: "Jack Kayil", position: "G" },
    { name: "Tyler Kolek", position: "G" },
    { name: "Miles McBride", position: "G" },
    { name: "Kevin McCullar Jr.", position: "G" },
    { name: "Tyler Nickel", position: "F" },
    { name: "Landry Shamet", position: "G" },
    { name: "Karl-Anthony Towns", position: "C" }
]
    },
    "oklahoma-city-thunder": {
        name: "Oklahoma City Thunder",
        abbreviation: "OKC",
        conference: "Western Conference",
        division: "Northwest",
        "2526": {
            wins: "64",
            losses: "18",
            winPercent: "78.0%",
            gamesBack: "-",
            teamPPG: "119.0",
teamRPG: "44.1",
teamAPG: "25.8",
teamSPG: "9.7",
teamBPG: "5.5",
teamFG: "48.4%",
teamThree: "36.5%",
        },
        "2425": {
    wins: "68",
    losses: "14",
    winPercent: "82.9%",
    gamesBack: "-",
    teamPPG: "120.5",
teamRPG: "44.2",
teamAPG: "26.9",
teamSPG: "9.1",
teamBPG: "5.7",
teamFG: "47.9%",
teamThree: "37.4%"
},
        roster: [
    { name: "Brooks Barnhizer", position: "F" },
    { name: "Alex Caruso", position: "G" },
    { name: "Josh Dix", position: "G" },
    { name: "Shai Gilgeous-Alexander", position: "G" },
    { name: "Isaiah Hartenstein", position: "C" },
    { name: "Chet Holmgren", position: "C" },
    { name: "Aday Mara", position: "C" },
    { name: "Jared McCain", position: "G" },
    { name: "Ajay Mitchell", position: "G" },
    { name: "Otega Oweh", position: "G" },
    { name: "Thomas Sorber", position: "C" },
    { name: "Bennett Stirtz", position: "G" },
    { name: "Nikola Topic", position: "G" },
    { name: "Cason Wallace", position: "G" },
    { name: "Jalen Williams", position: "G" },
    { name: "Jaylin Williams", position: "F" },
    { name: "Kenrich Williams", position: "G" }
]
    },
    "orlando-magic": {
        name: "Orlando Magic",
        abbreviation: "ORL",
        conference: "Eastern Conference",
        division: "Southeast",
        "2526": {
            wins: "45",
            losses: "37",
            winPercent: "54.9%",
            gamesBack: "15.0",
            teamPPG: "115.7",
teamRPG: "43.4",
teamAPG: "26.5",
teamSPG: "8.5",
teamBPG: "4.7",
teamFG: "46.4%",
teamThree: "34.3%"
        },
        "2425": {
    wins: "41",
    losses: "41",
    winPercent: "50.0%",
    gamesBack: "23.0",
    teamPPG: "105.4",
teamRPG: "41.8",
teamAPG: "23.0",
teamSPG: "8.9",
teamBPG: "6.0",
teamFG: "44.5%",
teamThree: "31.8%"
},
        roster: [
    { name: "Paolo Banchero", position: "F" },
    { name: "Desmond Bane", position: "G" },
    { name: "Goga Bitadze", position: "C" },
    { name: "Anthony Black", position: "G" },
    { name: "Malaki Branham", position: "F" },
    { name: "Jamal Cain", position: "F" },
    { name: "Jevon Carter", position: "G" },
    { name: "Wendell Carter Jr.", position: "C" },
    { name: "Colin Castleton", position: "C" },
    { name: "Tristan da Silva", position: "F" },
    { name: "JD Davison", position: "G" },
    { name: "Jonathan Isaac", position: "F" },
    { name: "Alex Morales", position: "G" },
    { name: "Izaiyah Nelson", position: "F" },
    { name: "Noah Penda", position: "F" },
    { name: "Jase Richardson", position: "G" },
    { name: "Jalen Suggs", position: "G" },
    { name: "Nikola Vucevic", position: "C" },
    { name: "Franz Wagner", position: "F" }
]
    },
    "philadelphia-76ers": {
        name: "Philadelphia 76ers",
        abbreviation: "PHI",
        conference: "Eastern Conference",
        division: "Atlantic",
        "2526": {
            wins: "45",
            losses: "37",
            winPercent: "54.9%",
            gamesBack: "15.0",
            teamPPG: "115.9",
teamRPG: "43.6",
teamAPG: "24.6",
teamSPG: "9.1",
teamBPG: "5.7",
teamFG: "46.2%",
teamThree: "34.9%"
        },
        "2425": {
    wins: "24",
    losses: "58",
    winPercent: "29.3%",
    gamesBack: "37.0",
    teamPPG: "109.6",
teamRPG: "39.8",
teamAPG: "23.2",
teamSPG: "9.2",
teamBPG: "4.5",
teamFG: "45.4%",
teamThree: "34.1%"
},
        roster: [
    { name: "Dominick Barlow", position: "F" },
    { name: "Adem Bona", position: "C" },
    { name: "Jaylen Brown", position: "G" },
    { name: "Kentavious Caldwell-Pope", position: "G" },
    { name: "VJ Edgecombe", position: "G" },
    { name: "Justin Edwards", position: "F" },
    { name: "Joel Embiid", position: "C" },
    { name: "Tacko Fall", position: "C" },
    { name: "Ariel Hukporti", position: "C" },
    { name: "LeBron James", position: "F" },
    { name: "Dillon Jones", position: "F" },
    { name: "Caleb Love", position: "G" },
    { name: "Tyrese Maxey", position: "G" },
    { name: "Duke Miles", position: "G" },
    { name: "Jameer Nelson Jr.", position: "G" },
    { name: "Labaron Philon Jr.", position: "G" },
    { name: "Rayan Rupert", position: "G" },
    { name: "Anfernee Simons", position: "G" },
    { name: "Dean Wade", position: "F" },
    { name: "Jabari Walker", position: "F" }
]
    },
    "phoenix-suns": {
        name: "Phoenix Suns",
        abbreviation: "PHX",
        conference: "Western Conference",
        division: "Pacific",
        "2526": {
            wins: "45",
            losses: "37",
            winPercent: "54.9%",
            gamesBack: "19.0",
            teamPPG: "112.6",
teamRPG: "43.1",
teamAPG: "24.6",
teamSPG: "9.5",
teamBPG: "4.2",
teamFG: "45.5%",
teamThree: "36.1%"
        },
        "2425": {
    wins: "36",
    losses: "46",
    winPercent: "43.9%",
    gamesBack: "32.0",
    teamPPG: "113.6",
teamRPG: "42.5",
teamAPG: "27.8",
teamSPG: "7.2",
teamBPG: "4.8",
teamFG: "47.8%",
teamThree: "37.8%"
},
        roster: [
    { name: "Devin Booker", position: "G" },
    { name: "Jamaree Bouyea", position: "G" },
    { name: "Koby Brea", position: "G" },
    { name: "Miles Bridges", position: "F" },
    { name: "Dillon Brooks", position: "F" },
    { name: "Ryan Dunn", position: "F" },
    { name: "Rasheer Fleming", position: "F" },
    { name: "Collin Gillespie", position: "G" },
    { name: "Jordan Goodwin", position: "G" },
    { name: "Jalen Green", position: "G" },
    { name: "Haywood Highsmith", position: "F" },
    { name: "CJ Huntley", position: "F" },
    { name: "Oso Ighodaro", position: "F" },
    { name: "Luke Kennard", position: "G" },
    { name: "Isaiah Livers", position: "F" },
    { name: "Khaman Maluach", position: "C" },
    { name: "Koa Peat", position: "F" },
    { name: "Duop Reath", position: "C" },
    { name: "Pat Spencer", position: "G" },
    { name: "Mark Williams", position: "C" }
]
    },
    "portland-trail-blazers": {
        name: "Portland Trail Blazers",
        abbreviation: "POR",
        conference: "Western Conference",
        division: "Northwest",
        "2526": {
            wins: "42",
            losses: "40",
            winPercent: "51.2%",
            gamesBack: "22.0",
            teamPPG: "115.5",
teamRPG: "46.0",
teamAPG: "25.1",
teamSPG: "8.3",
teamBPG: "5.5",
teamFG: "45.3%",
teamThree: "34.3%"
        },
        "2425": {
    wins: "36",
    losses: "46",
    winPercent: "43.9%",
    gamesBack: "32.0",
    teamPPG: "110.9",
teamRPG: "44.8",
teamAPG: "23.8",
teamSPG: "8.3",
teamBPG: "5.3",
teamFG: "45.0%",
teamThree: "34.2%"
},
        roster: [
    { name: "Deni Avdija", position: "F" },
    { name: "Toumani Camara", position: "F" },
    { name: "Branden Carlson", position: "C" },
    { name: "Sidy Cissoko", position: "G" },
    { name: "Donovan Clingan", position: "C" },
    { name: "Yang Hansen", position: "C" },
    { name: "Scoot Henderson", position: "G" },
    { name: "Jrue Holiday", position: "G" },
    { name: "Jayson Kent", position: "G" },
    { name: "Vit Krejci", position: "G" },
    { name: "Damian Lillard", position: "G" },
    { name: "Ja Morant", position: "G" },
    { name: "Micah Potter", position: "C" },
    { name: "Shaedon Sharpe", position: "G" },
    { name: "Jeremy Sochan", position: "F" },
    { name: "John Tonje", position: "F" },
    { name: "Robert Williams III", position: "C" },
    { name: "Chris Youngblood", position: "G" }
]
    },
    "sacramento-kings": {
        name: "Sacramento Kings",
        abbreviation: "SAC",
        conference: "Western Conference",
        division: "Pacific",
        "2526": {
            wins: "22",
            losses: "60",
            winPercent: "26.8%",
            gamesBack: "42.0",
            teamPPG: "111.0",
teamRPG: "42.3",
teamAPG: "25.5",
teamSPG: "8.0",
teamBPG: "4.5",
teamFG: "46.7%",
teamThree: "34.0%"
        },
        "2425": {
    wins: "40",
    losses: "42",
    winPercent: "48.8%",
    gamesBack: "28.0",
    teamPPG: "115.7",
teamRPG: "44.2",
teamAPG: "26.5",
teamSPG: "7.6",
teamBPG: "4.4",
teamFG: "47.8%",
teamThree: "35.7%"
},
        roster: [
    { name: "Precious Achiuwa", position: "PF" },
    { name: "Darius Acuff Jr.", position: "G" },
    { name: "Dylan Cardwell", position: "C" },
    { name: "Nique Clifford", position: "G" },
    { name: "Adam Flagler", position: "G" },
    { name: "De'Andre Hunter", position: "F" },
    { name: "Alex Karaban", position: "F" },
    { name: "Zach LaVine", position: "G" },
    { name: "Jonathan Mogbo", position: "F" },
    { name: "Malik Monk", position: "G" },
    { name: "Keegan Murray", position: "F" },
    { name: "Daeqwon Plowden", position: "G" },
    { name: "Maxime Raynaud", position: "C" },
    { name: "Domantas Sabonis", position: "F" },
    { name: "Emanuel Sharp", position: "G" },
    { name: "Ben Simmons", position: "G" }
]
    },
    "san-antonio-spurs": {
        name: "San Antonio Spurs",
        abbreviation: "SAS",
        conference: "Western Conference",
        division: "Southwest",
        "2526": {
        wins: "62",
        losses: "20",
        winPercent: "75.6%",
            gamesBack: "2.0",
        teamPPG: "119.8",
teamRPG: "47.0",
teamAPG: "28.1",
teamSPG: "7.5",
teamBPG: "5.5",
teamFG: "48.3%",
teamThree: "35.9%"
        },
        "2425": {
    wins: "34",
    losses: "48",
    winPercent: "41.5%",
    gamesBack: "34.0",
    teamPPG: "113.9",
teamRPG: "43.7",
teamAPG: "28.6",
teamSPG: "8.2",
teamBPG: "5.5",
teamFG: "46.5%",
teamThree: "35.7%"
},
        roster: [
    { name: "Harrison Barnes", position: "F" },
    { name: "Maliq Brown", position: "F" },
    { name: "Carter Bryant", position: "F" },
    { name: "Stephon Castle", position: "G" },
    { name: "Julian Champagnie", position: "F" },
    { name: "De'Aaron Fox", position: "G" },
    { name: "Ja'Kobi Gillespie", position: "G" },
    { name: "Dylan Harper", position: "G" },
    { name: "Tobias Harris", position: "F" },
    { name: "Harrison Ingram", position: "F" },
    { name: "Keldon Johnson", position: "F" },
    { name: "David Jones Garcia", position: "F" },
    { name: "Luke Kornet", position: "C" },
    { name: "Jordan McLaughlin", position: "G" },
    { name: "Emanuel Miller", position: "F" },
    { name: "Jayden Quaintance", position: "F" },
    { name: "Tarris Reed Jr.", position: "C" },
    { name: "Devin Vassell", position: "G" },
    { name: "Victor Wembanyama", position: "F" }
]
    },
    "toronto-raptors": {
        name: "Toronto Raptors",
        abbreviation: "TOR",
        conference: "Eastern Conference",
        division: "Atlantic",
        "2526": {
            wins: "46",
            losses: "36",
            winPercent: "56.1%",
            gamesBack: "14.0",
            teamPPG: "114.6",
teamRPG: "42.1",
teamAPG: "29.5",
teamSPG: "8.8",
teamBPG: "4.8",
teamFG: "48.2%",
teamThree: "35.4%"
        },
        "2425": {
    wins: "30",
    losses: "52",
    winPercent: "36.6%",
    gamesBack: "31.0",
    teamPPG: "110.9",
teamRPG: "45.1",
teamAPG: "28.5",
teamSPG: "8.1",
teamBPG: "4.2",
teamFG: "45.8%",
teamThree: "34.8%"
},
        roster: [
    { name: "Kyle Anderson", position: "F" },
    { name: "Scottie Barnes", position: "F" },
    { name: "RJ Barrett", position: "F" },
    { name: "Jamison Battle", position: "F" },
    { name: "Nate Bittle", position: "C" },
    { name: "Jaden Bradley", position: "G" },
    { name: "Allen Graves", position: "F" },
    { name: "Chucky Hepburn", position: "G" },
    { name: "Andre Jackson Jr.", position: "G" },
    { name: "Trayce Jackson-Davis", position: "F" },
    { name: "Trey Jemison III", position: "C" },
    { name: "A.J. Lawson", position: "G" },
    { name: "Kawhi Leonard", position: "F" },
    { name: "Alijah Martin", position: "G" },
    { name: "Collin Murray-Boyles", position: "F" },
    { name: "Jakob Poeltl", position: "C" },
    { name: "Immanuel Quickley", position: "G" },
    { name: "Jamal Shead", position: "G" },
    { name: "Ja'Kobe Walter", position: "G" }
]
    },
    "utah-jazz": {
        name: "Utah Jazz",
        abbreviation: "UTA",
        conference: "Western Conference",
        division: "Northwest",
        "2526": {
            wins: "22",
            losses: "60",
            winPercent: "26.8%",
            gamesBack: "42.0",
            teamPPG: "117.6",
teamRPG: "43.8",
teamAPG: "29.6",
teamSPG: "8.9",
teamBPG: "3.8",
teamFG: "46.7%",
teamThree: "34.5%"
        },
        "2425": {
    wins: "17",
    losses: "65",
    winPercent: "20.7%",
    gamesBack: "51.0",
    teamPPG: "111.9",
teamRPG: "45.4",
teamAPG: "25.5",
teamSPG: "6.8",
teamBPG: "4.4",
teamFG: "45.4%",
teamThree: "35.0%"
},
        roster: [
    { name: "Trey Alexander", position: "G" },
    { name: "Ace Bailey", position: "G" },
    { name: "Mo Bamba", position: "C" },
    { name: "Tamar Bates", position: "G" },
    { name: "Isaiah Collier", position: "G" },
    { name: "Kyle Filipowski", position: "F" },
    { name: "Keyonte George", position: "G" },
    { name: "Josh Green", position: "G" },
    { name: "Jaxson Hayes", position: "C" },
    { name: "Blake Hinson", position: "F" },
    { name: "Jaren Jackson Jr.", position: "F" },
    { name: "Lauri Markkanen", position: "F" },
    { name: "Svi Mykhailiuk", position: "G" },
    { name: "Jusuf Nurkic", position: "C" },
    { name: "Josh Okogie", position: "G" },
    { name: "Darryn Peterson", position: "G" },
    { name: "Brice Sensabaugh", position: "F" },
    { name: "Oscar Tshiebwe", position: "C" }
]
    },
    "washington-wizards": {
        name: "Washington Wizards",
        abbreviation: "WAS",
        conference: "Eastern Conference",
        division: "Southeast",
        "2526": {
            wins: "17",
            losses: "65",
            winPercent: "20.7%",
            gamesBack: "43.0",
            teamPPG: "112.9",
teamRPG: "41.9",
teamAPG: "25.0",
teamSPG: "8.0",
teamBPG: "5.5",
teamFG: "46.3%",
teamThree: "35.9%"
        },
        "2425": {
    wins: "18",
    losses: "64",
    winPercent: "22.0%",
    gamesBack: "43.0",
    teamPPG: "108.0",
teamRPG: "43.7",
teamAPG: "25.1",
teamSPG: "7.6",
teamBPG: "5.1",
teamFG: "43.9%",
teamThree: "33.5%"
},
        roster: [
    { name: "Deandre Ayton", position: "C" },
    { name: "Bub Carrington", position: "G" },
    { name: "Justin Champagnie", position: "F" },
    { name: "Sharife Cooper", position: "G" },
    { name: "Bilal Coulibaly", position: "G" },
    { name: "Anthony Davis", position: "F" },
    { name: "AJ Dybantsa", position: "F" },
    { name: "Kyshawn George", position: "F" },
    { name: "Anthony Gill", position: "F" },
    { name: "Tre Johnson", position: "G" },
    { name: "Tre Mann", position: "G" },
    { name: "Khris Middleton", position: "F" },
    { name: "Felix Okpara", position: "F" },
    { name: "Will Riley", position: "G" },
    { name: "Alex Sarr", position: "C" },
    { name: "Tristan Vukcevic", position: "F" },
    { name: "Jamir Watkins", position: "G" },
    { name: "Trae Young", position: "G" }
]
    }
};